### ISSUE TITLE
Adapt to braindecode

### ISSUE THREAD

**Issue by bruAristimunha** [elouayas/EEGSimpleConv#2]
Hello, @elouayas!

Do you have time to port your code to braindecode? I am still waiting for our last conversations hahaha
I will do something with the braindecode's models, and I think would be nice to have your model. 

Analyzing your model code looks like would be necessary only to change the variable names, create some tests, and create some doc strings.

This could potentially increase the use of your model.

All the best!

**Comment by bruAristimunha** [comment]
Pinging @elouayas

**Comment by elouayas** [comment]
It is a very nice suggestion !! Sorry for the late reply hahaha !
I am on it :) !
